### ISSUE TITLE
add functionality to java class class file to allow for point based classes

### ISSUE THREAD

**Issue by ghost** [Alpha-Beta-Gamma/Project1#25]

**Comment by gbsuccar** [comment]
I have added the finalCalculate method to Course.  Along with this, there is also a second constructor in Course that will allow for the addition of a boolean flag, percentBased, true if class is out of percent, false if class is out of points.  When finalCalculate is called, it will return the final grade needed regardless if the class is out of points or percent, assuming that it was sent a HashMap<String, Integer> that is also on the point system.

Issue: When testing, I found that if I had a class with a distribution that was out of 300 points, a final that is worth 100 of those points, and an obtained of 200 points, the final grade needed returned was 99.9999999999.  I've heard of "Off By One" errors, but this is ridiculous.

A note: When calling finalCalculate(HashMap<String, Integer> obtained, int goal),the HashMap is assumed to be point values,however the "goal" sent to the method is still assuming that it is out of percent, do you think I should make goal also a point value?
